{{- include "path-finder-service-common.secret" (list . "path-finder-postgresql.secret") -}}
{{- define "path-finder-postgresql.secret" -}}
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
{{- end -}}
