version: '3.8'

services:
  configuration:
    build: ./Configuration
    container_name: configuration
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_ADDRESS: ${RABBITMQ_ADDRESS}
      GIT_URI: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
      PORT: ${CONFIGURATION_PORT}
      CONFIG_KEY: ${CONFIG_KEY}
      PASSPHRASE: ${PASSPHRASE}
  security:
    build: ./Security
    container_name: security
    environment:
      CONFIG_URI: http://configuration:${CONFIGURATION_PORT}
      PORT: ${SECURITY_PORT}
    ports:
      - "${SECURITY_PORT}:${SECURITY_PORT}"
    depends_on:
      postgresql:
        condition: service_healthy
  indexer:
    build: ./Indexer
    container_name: indexer
    environment:
      CONFIG_URI: http://configuration:${CONFIGURATION_PORT}
      PORT: ${INDEXER_PORT}
    ports:
      - "${INDEXER_PORT}:${INDEXER_PORT}"
    depends_on:
      postgresql:
        condition: service_healthy
  searcher:
    build: ./Searcher
    container_name: searcher
    environment:
      CONFIG_URI: http://configuration:${CONFIGURATION_PORT}
      PORT: ${SEARCHER_PORT}
    ports:
      - "${SEARCHER_PORT}:${SEARCHER_PORT}"
  rabbitmq:
    image: rabbitmq:3.12.12-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  postgresql:
    image: postgres:15.3
    container_name: postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  neo4j:
    image: neo4j:5.15.0
    container_name: neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4J_server_default__listen__address: neo4j
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_memory_transaction_total_max: 0
      NEO4J_server_default__advertised__address: neo4j
      NEO4J_server_bolt_advertised__address: :${NEO4J_PORT}
      NEO4J_initial_dbms_default__database: ${NEO4J_DB_NAME}
    restart: on-failure
  liquibase:
    build: ./migration
    container_name: liquibase
    environment:
      LIQUIBASE_PROJECT_DIR: ${HOME}/migration
      LIQUIBASE_DATABASE_URL: jdbc:postgresql://postgresql:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
      LIQUIBASE_DATABASE_USERNAME: ${POSTGRES_USERNAME}
      LIQUIBASE_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgresql:
        condition: service_healthy