image:
  pullPolicy: Always
  repository: dkamakin/path-finder-configuration

service:
  port: 8888

git:
  uri: ""
  key: ""
  passphrase: ""

includeChartSecret: true
includeChartConfig: true

envFrom:
  extraClusterSecret:
    - chartName: path-finder-rabbitmq
