replicaCount: 1

image:
  repository: ""
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }
# fsGroup: 2000

env: { }

job:
  restartPolicy: Never

includeChartConfig: true
includeChartSecret: true

envFrom:
  extraClusterConfigmap: []
  extraClusterSecret: []

securityContext: { }

service:
  type: ClusterIP
  port: 80

resources: { }

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Additional volumes on the output Deployment definition.
volumes: [ ]
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: [ ]
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: { }

tolerations: [ ]

affinity: { }