spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_JDBC_URI}
  rabbitmq:
    password: ${RABBITMQ_PASSWORD}
    username: ${RABBITMQ_USERNAME}
    host: ${RABBITMQ_HOST}
  application:
    name: indexer
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 500
        max-attempts: 20
        multiplier: 1.3
        max-interval: 30000
  config:
    import: configserver:${CONFIG_URI}