spring:
  rabbitmq:
    password: ${RABBITMQ_PASSWORD}
    username: ${RABBITMQ_USERNAME}
    host: ${RABBITMQ_HOST}
  cloud:
    config:
      server:
        git:
          private-key: ${CONFIG_KEY}
          clone-on-start: true
          ignore-local-ssh-settings: true
          passphrase: ${PASSPHRASE}
          refresh-rate: 60
          uri: ${GIT_URI}
  application:
    name: configuration