{{- include "path-finder-service-common.secret" (list . "path-finder-configuration.secret") -}}
{{- define "path-finder-configuration.secret" -}}
data:
  CONFIG_KEY: {{ .Values.git.key }}
  PASSPHRASE: {{ .Values.git.passphrase | b64enc }}
  GIT_URI: {{ .Values.git.uri | b64enc }}
{{- end -}}
