{{- include "path-finder-service-common.configmap" (list . "path-finder-neo4j.configmap") -}}
{{- define "path-finder-neo4j.configmap" -}}
data:
  NEO4J_server_bolt_advertised__address: {{ .Values.service.port | quote }}
{{- end -}}
