apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "path-finder-service-common.fullname" . }}
  labels:
    {{- include "path-finder-service-common.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ required "capacity.storage is required (e.g. 10Gi)" .Values.capacity.storage | quote }}
  hostPath:
    path: {{ required "hostPath is required (e.g. /neo4j)" .Values.hostPath | quote }}
    type: Directory
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "path-finder-service-common.fullname" . }}
  labels:
    {{- include "path-finder-service-common.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  volumeName: {{ include "path-finder-service-common.fullname" . }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "capacity.storage is required (e.g. 10Gi)" .Values.capacity.storage }}