{{- include "path-finder-service-common.secret" (list . "path-finder-neo4j.secret") -}}
{{- define "path-finder-neo4j.secret" -}}
data:
  NEO4J_PASSWORD: {{ .Values.authentication.password | b64enc }}
  NEO4J_USERNAME: {{ .Values.authentication.username | b64enc }}
  NEO4J_AUTH: {{ .Values.authentication.credentials | b64enc }}
  NEO4J_initial_dbms_default__database: {{ .Values.databaseName | b64enc }}
{{- end -}}
