image:
  pullPolicy: Always
  repository: dkamakin/path-finder-migration

job:
  restartPolicy: Never

includeChartConfig: false
includeChartSecret: false

resources: { }

envFrom:
  extraClusterSecret:
    - chartName: path-finder-postgresql
    - chartName: path-finder-neo4j
  extraClusterConfigmap:
    - chartName: path-finder-postgresql-public
    - chartName: path-finder-neo4j-public
