service:
  port: 7687

image:
  pullPolicy: IfNotPresent
  repository: neo4j
  tag: 5.15.0-community-ubi8

# Sets the Neo4j username/password. The credentials are changed only on the first start.
authentication:
  credentials: ""
  username: ""
  password: ""

# The neo4j default database name.
databaseName: ""

includeChartSecret: true
includeChartConfig: true

envFrom: { }

env:
  - name: NEO4J_server_config_strict__validation_enabled
    value: 'false'
  - name: NEO4J_PLUGINS
    value: '["apoc"]'
  - name: NEO4J_db_memory_pagecache_warmup_enable
    value: "true"
  - name: NEO4J_dbms_security_procedures_unrestricted
    value: "apoc.*"
  - name: NEO4J_dbms_memory_transaction_total_max
    value: "0"