{{- include "path-finder-service-common.secret" (list . "path-finder-rabbitmq.secret") -}}
{{- define "path-finder-rabbitmq.secret" -}}
data:
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password | b64enc }}
  RABBITMQ_HOST: {{ include "path-finder-service-common.fullnameGenerator" (dict "chartName" "rabbitmq" "Values" .Values "Release" .Release) | b64enc }}
{{- end -}}
