spring:
  rabbitmq:
    password: ${RABBITMQ_PASSWORD}
    username: ${RABBITMQ_USERNAME}
    addresses: ${RABBITMQ_ADDRESS}
  application:
    name: searcher
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 500
        max-attempts: 20
        multiplier: 1.3
        max-interval: 30000
  config:
    import: configserver:${CONFIG_URI}