spring:
  application:
    name: searcher
  cloud:
    config:
      retry:
        initial-interval: 500
        max-attempts: 20
        multiplier: 1.3
        max-interval: 30000
      fail-fast: true
  config:
    import: configserver:${CONFIG_URI}
server:
  port: ${PORT}