name: Build

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: A tag name to use when publishing images. By default a branch name is taken.
        required: false
        type: string
  release:
    types: published

env:
  TAG_NAME: ${{ inputs.tagName || github.ref_name || github.head_ref }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: 21

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Java images
        run: ./gradlew jib

      - name: Migration build and push
        uses: dkamakin/pathfinder-docker-publish-action@v1
        with:
          context: ./migration
          tags: dkamakin/path-finder-migration:${{ env.TAG_NAME }}
