name: Build

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: A tag name to use when publishing images
        required: false
        type: string
  push:
    branches:
      - main

env:
  TAG_NAME: ${{ inputs.tagName || github.head_ref || github.ref_name }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Info step
        run: echo A current tag name is $TAG_NAME

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2

      - name: Execute build
        run: ./gradlew build -x test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configuration build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Configuration
          push: true
          tags: dkamakin/path-finder-configuration:${{ env.TAG_NAME }}
