name: Build

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: A tag name to use when publishing images. By default a branch name is taken.
        required: false
        type: string
  release:
    types: published

env:
  TAG_NAME: ${{ inputs.tagName || github.ref_name || github.head_ref }}
  REGISTRY_URL: registry.hub.docker.com/dkamakin

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Wrap the services into Docker
        run: ./gradlew jib

      - name: Migration build and push
        uses: dkamakin/pathfinder-docker-publish-action@v1
        with:
          context: ./migration
          file: ./migration/Dockerfile
          tags: dkamakin/path-finder-migration:${{ env.TAG_NAME }}
