name: Build

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: Images tag name
        required: true
        type: string
  push:

env:
  TAG_NAME: ${{ inputs.tagName || github.head_ref || github.ref_name }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configuration build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dkamakin/path-finder-configuration:$TAG_NAME
