name: Test

on: [ push, pull_request ]

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Setup Gradle and execute tests
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: testReleaseUnitTest

      - name: Publish test reports
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: JUnit tests
          path: './**/build/test-results/**/TEST-*.xml'
          reporter: java-junit