name: Test

on:
  pull_request:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2

      - name: Execute build and run tests
        run: ./gradlew build test

      - name: Publish test reports
        uses: dorny/test-reporter@v1.9.0
        if: always()
        with:
          name: JUnit tests
          path: './**/build/test-results/**/TEST-*.xml'
          reporter: java-junit