name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@a494d935f4b56874c4a5a87d19af7afcf3a163d0

      - name: Execute build and run tests
        run: ./gradlew build test

      - name: Publish test reports
        uses: dorny/test-reporter@v1.8.0
        if: always()
        with:
          name: JUnit tests
          path: './**/build/test-results/**/TEST-*.xml'
          reporter: java-junit