name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Execute build and run tests
        run: ./gradlew build test

      - name: Publish test reports
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: JUnit tests
          path: './**/build/test-results/**/TEST-*.xml'
          reporter: java-junit