name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.12.0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4

      - name: Execute build and run tests
        run: ./gradlew build test

      - name: Publish test reports
        uses: dorny/test-reporter@v1.8.0
        if: always()
        with:
          name: JUnit tests
          path: './**/build/test-results/**/TEST-*.xml'
          reporter: java-junit