image:
  pullPolicy: Always
  repository: dkamakin/path-finder-searcher

service:
  port: 8080

resources: { }

includeChartSecret: false
includeChartConfig: true

envFrom:
  extraClusterSecret:
    - chartName: path-finder-rabbitmq
    - chartName: path-finder-neo4j
  extraClusterConfigmap:
    - chartName: path-finder-configuration-public
    - chartName: path-finder-neo4j-public
